#include <iostream>
using namespace std;

int main()
{
	setlocale(0, "ru");
	int a_1 = 10;
	int a_2 = 20;
	int a_3 = 30;
	int a_4 = 40;
	int a_5 = 50;
	int a_6 = 60;
	int a_7 = 70;
	int a_8 = 80;
	int a_9 = 90;
	int a_10 = 100;
	cout << "Тип данных int" << endl;
	cout << " [1] a_1 = " << a_1 << "| размер: 4 б." << endl;
	cout << " [2] a_2 = " << a_2 << "| размер: 4 б." << endl;
	cout << " [3] a_3 = " << a_3 << "| размер: 4 б." << endl;
	cout << " [4] a_4 = " << a_4 << "| размер: 4 б." << endl;
	cout << " [5] a_5 = " << a_5 << "| размер: 4 б." << endl;
	cout << " [6] a_6 = " << a_6 << "| размер: 4 б." << endl;
	cout << " [7] a_7 = " << a_7 << "| размер: 4 б." << endl;
	cout << " [8] a_8 = " << a_8 << "| размер: 4 б." << endl;
	cout << " [9] a_9 = " << a_9 << "| размер: 4 б." << endl;
	cout << " [10] a_10 = " << a_10 << "| размер: 4 б." << endl;

	long b_1 = 100;
	long b_2 = 200;
	long b_3 = 300;
	long b_4 = 400;
	long b_5 = 500;
	long b_6 = 600;
	long b_7 = 700;
	long b_8 = 800;
	long b_9 = 900;
	long b_10 = 1000;
	cout << "Тип данных long" << endl;
	cout << " [1] b_1 = " << b_1 << "| размер: 4 б." << endl;
	cout << " [2] b_2 = " << b_2 << "| размер: 4 б." << endl;
	cout << " [3] b_3 = " << b_3 << "| размер: 4 б." << endl;
	cout << " [4] b_4 = " << b_4 << "| размер: 4 б." << endl;
	cout << " [5] b_5 = " << b_5 << "| размер: 4 б." << endl;
	cout << " [6] b_6 = " << b_6 << "| размер: 4 б." << endl;
	cout << " [7] b_7 = " << b_7 << "| размер: 4 б." << endl;
	cout << " [8] b_8 = " << b_8 << "| размер: 4 б." << endl;
	cout << " [9] b_9 = " << b_9 << "| размер: 4 б." << endl;
	cout << " [10] b_10 = " << b_10 << "| размер: 4 б." << endl;

	short c_1 = 1;
	short c_2 = 2;
	short c_3 = 3;
	short c_4 = 4;
	short c_5 = 5;
	short c_6 = 6;
	short c_7 = 7;
	short c_8 = 8;
	short c_9 = 9;
	short c_10 = 10;
	cout << "Тип данных short" << endl;
	cout << " [1] c_1 = " << c_1 << "| размер: 2 б." << endl;
	cout << " [2] c_2 = " << c_2 << "| размер: 2 б." << endl;
	cout << " [3] c_3 = " << c_3 << "| размер: 2 б." << endl;
	cout << " [4] c_4 = " << c_4 << "| размер: 2 б." << endl;
	cout << " [5] c_5 = " << c_5 << "| размер: 2 б." << endl;
	cout << " [6] c_6 = " << c_6 << "| размер: 2 б." << endl;
	cout << " [7] c_7 = " << c_7 << "| размер: 2 б." << endl;
	cout << " [8] c_8 = " << c_8 << "| размер: 2 б." << endl;
	cout << " [9] c_9 = " << c_9 << "| размер: 2 б." << endl;
	cout << " [10] c_10 = " << c_10 << "| размер: 2 б." << endl;

	char d_1 = 'A';
	char d_2 = 'B';
	char d_3 = 'C';
	char d_4 = 'D';
	char d_5 = 'F';
	char d_6 = 'I';
	char d_7 = 'J';
	char d_8 = 'N';
	char d_9 = 'M';
	char d_10 =  'R';
	cout << "Тип данных char" << endl;
	cout << " [1] d_1 = " << d_1 << "| размер: 1 б." << endl;
	cout << " [2] d_2 = " << d_2 << "| размер: 1 б." << endl;
	cout << " [3] d_3 = " << d_3 << "| размер: 1 б." << endl;
	cout << " [4] d_4 = " << d_4 << "| размер: 1 б." << endl;
	cout << " [5] d_5 = " << d_5 << "| размер: 1 б." << endl;
	cout << " [6] d_6 = " << d_6 << "| размер: 1 б." << endl;
	cout << " [7] d_7 = " << d_7 << "| размер: 1 б." << endl;
	cout << " [8] d_8 = " << d_8 << "| размер: 1 б." << endl;
	cout << " [9] d_9 = " << d_9 << "| размер: 1 б." << endl;
	cout << " [10] d_10 = " << d_10 << "| размер: 1 б." << endl;

	bool f_1 = 1;
	bool f_2 = 0;
	bool f_3 = 1;
	bool f_4 = 0;
	bool f_5 = 1;
	bool f_6 = 0;
	bool f_7 = 1;
	bool f_8 = 1;
	bool f_9 = 0;
	bool f_10 = 1;
	cout << "Тип данных bool" << endl;
	cout << " [1] f_1 = " << f_1 << "| размер: 1 б." << endl;
	cout << " [2] f_2 = " << f_2 << "| размер: 1 б." << endl;
	cout << " [3] f_3 = " << f_3 << "| размер: 1 б." << endl;
	cout << " [4] f_4 = " << f_4 << "| размер: 1 б." << endl;
	cout << " [5] f_5 = " << f_5 << "| размер: 1 б." << endl;
	cout << " [6] f_6 = " << f_6 << "| размер: 1 б." << endl;
	cout << " [7] f_7 = " << f_7 << "| размер: 1 б." << endl;
	cout << " [8] f_8 = " << f_8 << "| размер: 1 б." << endl;
	cout << " [9] f_9 = " << f_9 << "| размер: 1 б." << endl;
	cout << " [10] f_10 = " << f_10 << "| размер: 1 б." << endl;

	float g_1 = 1.1;
	float g_2 = 1.2;
	float g_3 = 1.3;
	float g_4 = 1.4;
	float g_5 = 1.5;
	float g_6 = 1.6;
	float g_7 = 1.7;
	float g_8 = 1.8;
	float g_9 = 1.9;
	float g_10 = 1.10;
	cout << "Тип данных float" << endl;
	cout << " [1] g_1 = " << g_1 << "| размер: 4 б." << endl;
	cout << " [2] g_2 = " << g_2 << "| размер: 4 б." << endl;
	cout << " [3] g_3 = " << g_3 << "| размер: 4 б." << endl;
	cout << " [4] g_4 = " << g_4 << "| размер: 4 б." << endl;
	cout << " [5] g_5 = " << g_5 << "| размер: 4 б." << endl;
	cout << " [6] g_6 = " << g_6 << "| размер: 4 б." << endl;
	cout << " [7] g_7 = " << g_7 << "| размер: 4 б." << endl;
	cout << " [8] g_8 = " << g_8 << "| размер: 4 б." << endl;
	cout << " [9] g_9 = " << g_9 << "| размер: 4 б." << endl;
	cout << " [10] g_10 = " << g_10 << "| размер: 4 б." << endl;

	double h_1 = 1.11;
	double h_2 = 1.12;
	double h_3 = 1.13;
	double h_4 = 1.14;
	double h_5 = 1.15;
	double h_6 = 1.16;
	double h_7 = 1.17;
	double h_8 = 1.18;
	double h_9 = 1.19;
	double h_10 = 1.110;
	cout << "Тип данных double" << endl;
	cout << " [1] h_1 = " << h_1 << "| размер: 8 б." << endl;
	cout << " [2] h_2 = " << h_2 << "| размер: 8 б." << endl;
	cout << " [3] h_3 = " << h_3 << "| размер: 8 б." << endl;
	cout << " [4] h_4 = " << h_4 << "| размер: 8 б." << endl;
	cout << " [5] h_5 = " << h_5 << "| размер: 8 б." << endl;
	cout << " [6] h_6 = " << h_6 << "| размер: 8 б." << endl;
	cout << " [7] h_7 = " << h_7 << "| размер: 8 б." << endl;
	cout << " [8] h_8 = " << h_8 << "| размер: 8 б." << endl;
	cout << " [9] h_9 = " << h_9 << "| размер: 8 б." << endl;
	cout << " [10] h_10 = " << h_10 << "| размер: 8 б." << endl;

	string j_1 = "AB";
	string j_2 = "BC";
	string j_3 = "CD";
	string j_4 = "DF";
	string j_5 = "FG";
	string j_6 = "GJ";
	string j_7 = "HJ";
	string j_8 = "NM";
	string j_9 = "RF";
	string j_10 = "FF";
	cout << "Тип данных string" << endl;
	cout << " [1] j_1 = " << j_1 << "| размер: .. б." << endl;
	cout << " [2] j_2 = " << j_2 << "| размер: .. б." << endl;
	cout << " [3] j_3 = " << j_3 << "| размер: .. б." << endl;
	cout << " [4] j_4 = " << j_4 << "| размер: .. б." << endl;
	cout << " [5] j_5 = " << j_5 << "| размер: .. б." << endl;
	cout << " [6] j_6 = " << j_6 << "| размер: .. б." << endl;
	cout << " [7] j_7 = " << j_7 << "| размер: .. б." << endl;
	cout << " [8] j_8 = " << j_8 << "| размер: .. б." << endl;
	cout << " [9] j_9 = " << j_9 << "| размер: .. б." << endl;
	cout << " [10] j_10 = " << j_10 << "| размер: .. б." << endl;
}